apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-svc-cert
  labels:
    app: webhook-proxy
  name: webhook-proxy
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook-proxy
  sessionAffinity: None
