apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations: {}
  generation: 1
  labels:
    app: sfa-api
  name: job-worker
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: job-worker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: sfa-api
        deploymentconfig: job-worker
    spec:
      containers:
      - command:
          - /opt/app-root/bin/sfa-api
          - scheduled-worker
          - --job-monitoring-interval
          - "300"
          - /conf/job-config.py
        env:
        - name: SENTRY_DSN
          value: {{ sentry_dsn }}
        - name: HOME
          value: /opt/app-root/
        image: sfa-api:{{ sfa_api_image_tag | default('latest') }}
        imagePullPolicy: Always
        name: jobworker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: job-config
        - mountPath: /data
          name: data
        - mountPath: /opt/app-root/.plotly
          name: orca-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nwp-forecasts-archive-{{ namespace }}
      - name: job-config
        secret:
          defaultMode: 420
          secretName: sfa-api-job-config
      - name: orca-config
        configMap:
          name: orca-config
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jobworker
      from:
        kind: ImageStreamTag
        name: sfa-api:{{ sfa_api_image_tag | default('latest') }}
    type: ImageChange
  - type: ConfigChange
