apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations: {}
  generation: 1
  labels:
    app: sfa-api
  name: job-worker
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: job-worker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: sfa-api
        deploymentconfig: job-worker
    spec:
      initContainers:
      - name: make-ca
        command:
          - sh
          - -c
          - "cp /etc/ssl/certs/ca-certificates.crt /ca/. && cat /run/secrets/kubernetes.io/serviceaccount/service-ca.crt >> /ca/ca-certificates.crt"
        image: sfa-api:{{ sfa_api_image_tag | default('latest') }}
        volumeMounts:
        - mountPath: /ca
          name: combined-ca
      containers:
      - command:
          - /opt/app-root/bin/sfa-api
          - scheduled-worker
          - --job-monitoring-interval
          - "600"
          - --worker-ttl
          - "720"
          - /conf/job-config.py
        env:
        - name: SENTRY_DSN
          value: {{ worker_sentry_dsn }}
        - name: HOME
          value: /opt/app-root/
        - name: REQUESTS_CA_BUNDLE
          value: /ca/ca-certificates.crt
        image: sfa-api:{{ sfa_api_image_tag | default('latest') }}
        imagePullPolicy: Always
        name: jobworker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: job-config
        - mountPath: /data
          name: data
        - mountPath: /opt/app-root/.plotly
          name: orca-config
        - mountPath: /ca
          name: combined-ca
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nwp-forecasts-archive-{{ namespace }}
      - name: job-config
        secret:
          defaultMode: 420
          secretName: sfa-api-job-config
      - name: orca-config
        configMap:
          name: orca-config
      - name: combined-ca
        emptyDir: {}
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jobworker
      - make-ca
      from:
        kind: ImageStreamTag
        name: sfa-api:{{ sfa_api_image_tag | default('latest') }}
    type: ImageChange
  - type: ConfigChange
