apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    app: reference-forecasts
  name: nwp-forecasts-archive-{{ namespace }}
  namespace: "{{ namespace }}"
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: nwp-forecasts-archive-{{ namespace }}
status: {}
