apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-dash
  name: sfa-dash
  namespace: {{ namespace }}
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-dash:latest
  postCommit:
    command:
      - sh
      - -c
      - |
       pip install -r  https://raw.githubusercontent.com/SolarArbiter/solarforecastarbiter-core/master/requirements-test.txt
       pytest --pyargs solarforecastarbiter
       pip install -r https://raw.githubusercontent.com/SolarArbiter/solarforecastarbiter_dashboard/master/requirements-test.txt
       pip install pytest-custom_exit_code
       pytest --pyargs sfa_dash --suppress-no-test-exit-code
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/SolarArbiter/solarforecastarbiter_dashboard.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: sfa-core:latest
    type: Source
  successfulBuildsHistoryLimit: 3
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-dash-trigger
