apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-dash
  name: sfa-dash
  namespace: {{ namespace }}
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-dash:latest
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM quay.io/solararbiter/solarforecastarbiter-core:latest
      RUN git clone https://github.com/solararbiter/solarforecastarbiter-dashboard /opt/app-root/src && \
          cd /opt/app-root/src && \
          pip install -r requirements.txt && \
          pip install .
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: ImageStreamTag
        name: sfa-core:latest
    type: Source
  successfulBuildsHistoryLimit: 3
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-dash-trigger
