apiVersion: v1
kind: Secret
metadata:
  name: sfa-dash-gpg-secret
  namespace: {{ namespace }}
data:
  gpg-key-id: {{ gpg_key_id | b64encode }}
  passphrase.txt: {{ gpg_passphrase | b64encode }}
  key.gpg: {{ gpg_secret | b64encode }}
