apiVersion: v1
kind: Secret
metadata:
  name: sfa-dash-secret-config
  namespace: {{ namespace }}
data:
  flask-secret-key: {{ flask_secret_key | b64encode }}
  auth0-client-id: {{ auth0_client_id | b64encode }}
  auth0-client-secret: {{ auth0_client_secret | b64encode }}
  
