apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sfa-dash-monitor
  namespace: openshift-monitoring
  labels:
    k8s-app: sfa-dash
spec:
  namespaceSelector:
    matchNames:
      - development
      - production
  selector:
    matchLabels:
      app: sfa-dash
  endpoints:
  - port: prometheus
