apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reference-nwp
  labels:
    app: reference-nwp
  annotations: {}
  namespace: "{{ namespace }}"
spec:
  schedule: "{{ schedule }}"
  jobTemplate:
    spec:
      metadata:
        labels:
          app: reference-nwp
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: update-nwp
              image: sfa-core:{{ image_tag }}
              command:
                - sh
                - -c
                - solararbiter referencenwp -v --base-url="{{ base_url }}" /data
              volumeMounts:
                - mountPath: /data
                  name: data
              env:
                - name: SFA_API_USER
                  valueFrom:
                    secretKeyRef:
                      key: api-user
                      name: reference-data
                - name: SFA_API_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: api-password
                      name: reference-data
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      key: sentry-dsn
                      name: reference-data
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: nwp-forecasts-archive-{{ namespace }}
