apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.beta.kubernetes.io/mount-options: nfsvers=4,noac,proto=tcp,rsize=32768,wsize=32768,noatime,nodiratime
  labels:
    app: reference-nwp
  name: nwp-forecasts-archive-{{ namespace }}
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 20Gi
  nfs:
    path: /hdd/compute/nwp_forecasts
    server: core.solarforecastarbiter.org
  persistentVolumeReclaimPolicy: Retain
status: {}
