apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: python-extra
  name: python-extra
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: python-extra:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM python:latest
      USER root
      RUN yum install -y epel-release && \
          yum install -y --setopt=tsflags=nodocs wgrib2 && \
          yum clean all && \
          rm -rf /var/cache/yum
      RUN wget -q -P /tmp https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-linux.tar.gz && \
          tar xvzf /tmp/pandoc-2.7.3-linux.tar.gz --strip-components 1 -C /opt/app-root && \
          rm -f /tmp/pandoc-2.7.3-linux.tar.gz
      RUN chown -R 1001:0 ${APP_ROOT} && \
          fix-permissions ${APP_ROOT} -P && \
          mkdir /data && chown root:5555 /data && chmod 0775 /data
      USER 1001
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: ImageStreamTag
        name: python:latest
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
