apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "daily-reference-validation"
  labels:
    app: data-validation
  annotations: {}
  namespace: {{ namespace }}
spec:
  schedule: {{ schedule }}
  jobTemplate:
    spec:
      metadata:
        labels:
          app: data-validation
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: validate
              image: sfa-core:{{ image_tag }}
              command:
                - sh
                - -c
                - solararbiter dailyvalidation --base-url="{{ base_url }}" -v --end $(date -uIs -d "{{ end }}")
              env:
                - name: SFA_API_USER
                  value: {{ api_user }}
                - name: SFA_API_PASSWORD
                  value: {{ api_password }}
                - name: SENTRY_DSN
                  value: {{ sentry_dsn }}
          restartPolicy: Never
