apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: mysql
  namespace: {{ namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: glusterfs-storage

