apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mysql
  name: mysql
  namespace: {{ namespace }}
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
