apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-core
  name: sfa-core
  namespace: development
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-core:latest
  postCommit:
    command:
      - solararbiter
      - test
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM solarforecastarbiter-core:latest
      RUN git clone https://github.com/solararbiter/solarforecastarbiter-core /tmp/src && \
          cd /tmp/src && \
          pip install -r requirements.txt -r requirements-test.txt && \
          pip install ".[all]" && \
          rm -r /tmp/src
  strategy:
    dockerStrategy:
      forcePull: true
      noCache: true
      from:
        kind: DockerImage
        name: quay.io/solararbiter/solarforecastarbiter-core:latest
  successfulBuildsHistoryLimit: 3
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-core-trigger

