apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-core
  name: sfa-core
  namespace: development
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-core:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM python-extra:latest
      RUN git clone https://github.com/solararbiter/solarforecastarbiter-core /tmp/src && \
          shopt -s dotglob &&\
          cd /tmp/src && \
          pip install -r requirements.txt && \
          pip install ".[all]"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: ImageStreamTag
        name: python-extra:latest
  successfulBuildsHistoryLimit: 3
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-core-trigger

