apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-core
  name: sfa-core
  namespace: development
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-core:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM python:latest
      USER root
      RUN yum install -y epel-release && \
          yum install -y --setopt=tsflags=nodocs wgrib2 && \
          yum clean all && \
          rm -rf /var/cache/yum
      USER 1001
      RUN git clone https://github.com/solararbiter/solarforecastarbiter-core /tmp/src && \
          shopt -s dotglob &&\ 
          mv /tmp/src/* ./ && \
          pip install -r requirements.txt && \
          pip install ".[all]"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: ImageStreamTag
        name: python:latest
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-core-trigger

