apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  generation: 1
  labels:
    app: sfa-core
  name: sfa-core
  namespace: development
spec:
  lookupPolicy:
    local: true
