apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: {{ namespace }}
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
