apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: {{ namespace }}
roleRef:
  name: prometheus-k8s
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
userNames:
- system:serviceaccount:openshift-monitoring:prometheus-k8s
