apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ redis_name| default('redis') }}"
  labels:
    app: "{{ redis_app| default('redis') }}"
  namespace: {{ namespace }}
  annotations: {}
spec:
  storageClass: glusterfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
