apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ redis_app | default('redis') }}
  name: "{{ redis_name | default('redis') }}-auth"
  namespace: {{ namespace }}
data:
  redis-auth: {{ redis_auth | b64encode }}
