apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: "{{ redis_name | default('redis') }}-tls"
  labels:
    app: {{ redis_app | default('redis') }}
  name: {{ redis_name | default('redis') }}
  namespace: {{ namespace }}
spec:
  ports:
  - name: redis-ssl
    port: 6380
    protocol: TCP
    targetPort: 6380
  selector:
    deploymentconfig: {{ redis_name | default('redis') }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
