apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: sfa-api
  name: sfa-api
  namespace: {{ namespace }}
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sfa-api:latest
  postCommit:
    command:
      - sh
      - -c
      - |
       pip install -r  https://raw.githubusercontent.com/SolarArbiter/solarforecastarbiter-core/master/requirements-test.txt 
       pytest --pyargs solarforecastarbiter 
       pip install -r https://raw.githubusercontent.com/SolarArbiter/solarforecastarbiter-api/master/requirements-test.txt 
       pytest --pyargs sfa_api
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM quay.io/solararbiter/solarforecastarbiter-core:latest
      RUN git clone https://github.com/solararbiter/solarforecastarbiter-api /opt/app-root/src && \
          cd /opt/app-root/src && \
          pip install -r requirements.txt && \
          pip install ".[all]" 
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: ImageStreamTag
        name: sfa-core:latest
    type: Source
  successfulBuildsHistoryLimit: 3
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: sfa-api-trigger

