apiVersion: v1
kind: Secret
metadata:
  name: sfa-api-mysql-config
  namespace: {{ namespace }}
data:
  mysql-host: {{ mysql_host | b64encode }}
  mysql-port: {{ mysql_port | b64encode }}
  mysql-user: {{ mysql_user | b64encode }}
  mysql-password: {{ mysql_password | b64encode }}
  mysql-database: {{ mysql_database | b64encode }}
