apiVersion: v1
kind: Secret
metadata:
  name: sfa-api-mysql-config
  namespace: {{ namespace }}
data:
  MYSQL_HOST: {{ mysql_host | b64encode }}
  MYSQL_PORT: {{ mysql_port | b64encode }}
  MYSQL_USER: {{ mysql_user | b64encode }}
  MYSQL_PASSWORD: {{ mysql_password | b64encode }}
  MYSQL_DATABASE: {{ mysql_database | b64encode }}
