apiVersion: v1
kind: Secret
metadata:
  name: sfa-api-secrets
  namespace: {{ namespace }}
data:
  auth0-client-id: {{ auth0_client_id | b64encode }}
  auth0-client-secret: {{ auth0_client_secret | b64encode }}
