apiVersion: v1
kind: Secret
metadata:
  name: sfa-api-redis-config
  namespace: {{ namespace }}
data:
  redis-config.py: {{ (redis_config ~ '\nREDIS_PASSWORD = "' ~
      redis_auth ~ '"\nREDIS_HOST = "' ~ redis_host ~ '"')| b64encode }}
    
